# Generated by Django 5.2.6 on 2025-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon_class", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PartnerLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="partners/")),
                ("alt_text", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Card",
        ),
        migrations.DeleteModel(
            name="Partner",
        ),
        migrations.RenameField(
            model_name="about",
            old_name="about",
            new_name="about_text",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="icon",
            new_name="icon_class",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="comments_count",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="comments",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="about",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="Admin", max_length=100),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
