# Generated by Django 5.2.6 on 2025-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_homecard_partnerlogo_delete_card_delete_partner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True, null=True)),
                (
                    "button_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="button_link",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="button_text",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="title",
        ),
    ]
