# Generated by Django 5.2.6 on 2025-09-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_herocontent_remove_heroslide_button_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="video_url",
        ),
        migrations.AddField(
            model_name="about",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="about/"),
        ),
        migrations.AddField(
            model_name="about",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="about/videos/"),
        ),
    ]
