# Generated by Django 5.2.6 on 2025-09-07 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_blogpost_views_comment_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="likes",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="blog_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
