# Generated by Django 5.2.6 on 2025-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_blogpost_likes_blogpost_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="blogs/"),
        ),
    ]
