# Generated by Django 5.2.6 on 2025-09-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_blogpost_hero_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="hero_image",
        ),
    ]
