# Generated by Django 5.2.6 on 2025-09-08 13:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_blogpost_hero_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="hero_image",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
