# Generated by Django 5.2.6 on 2025-09-12 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_doctor_patient_message_appointment_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="hospital_id",
            field=models.CharField(
                default="", editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="doctors",
            field=models.ManyToManyField(
                blank=True, related_name="patients", to="core.doctor"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="hospital_id",
            field=models.CharField(
                default="", editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("pending", "Pending Approval"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
