# Generated by Django 5.2.6 on 2025-09-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_doctor_hospital_id_doctor_user_patient_doctors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="hospital_id",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="doctors",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="hospital_id",
        ),
        migrations.AddField(
            model_name="doctor",
            name="doctor_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="hospital_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("pending", "Pending"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
