# Generated by Django 5.2.6 on 2025-09-12 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_doctor_hospital_id_remove_doctor_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.AddField(
            model_name="message",
            name="recipient_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_messages",
                to="core.doctor",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient_patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_messages",
                to="core.patient",
            ),
        ),
    ]
