# Generated by Django 5.2.6 on 2025-09-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_message_recipient_message_recipient_doctor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="department",
        ),
    ]
