# Generated by Django 5.2.6 on 2025-09-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_patient_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="recipient_patient",
        ),
    ]
