# Generated by Django 5.2.6 on 2025-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_message_recipient_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
