# Generated by Django 5.2.6 on 2025-09-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_doctor_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialty",
            field=models.CharField(default="General", max_length=100),
        ),
    ]
