# Generated by Django 5.2.6 on 2025-09-17 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_department_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="core.appointment",
            ),
        ),
    ]
