# Generated by Django 5.2.6 on 2025-09-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_report_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
